[package]
name = "tweetter"
version = "0.1.0"
authors = ["nodebotanist <the@nodebotani.st>"]
edition = "2018"
repository = "https://github.com/nodebotanist/tweeter"

[dependencies]
clap = "~2.33.0"
clipboard = "0.5.0"
